namespace VivantioApiInteractive.Dtos;

internal record TicketBaseDto
{
    public int Id { get; init; }
    public DateTime OpenDate { get; init; }
    public DateTime CloseDate { get; init; }
    public string? CallerName { get; init; }
    public int TakenById { get; init; }
    public int OwnerId { get; init; }
    public int ThirdPartyId { get; init; }
    public string? ThirdPartyRef { get; init; }
    public DateTime ThirdPartyLogDate { get; init; }
    public int PriorityId { get; init; }
    public StatusType? StatusType { get; init; }
    public string? Description { get; init; }
    public int CategoryId { get; init; }
    public string? Solution { get; init; }
    public int LocationId { get; init; }
    public int LastActionId { get; init; }
    public string? CallerPhone { get; init; }
    public string? CallerEmail { get; init; }
    public int TotalEffort { get; init; }
    public int LastModifiedById { get; init; }
    public DateTime LastModifiedDate { get; init; }
    public int GroupId { get; init; }
    public int ClientId { get; init; }
    public int StatusId { get; init; }
    public int ImpactId { get; init; }
    public int CallerId { get; init; }
    public string? PriorityName { get; init; }
    public string? TakenByName { get; init; }
    public string? GroupName { get; init; }
    public string? OwnerName { get; init; }
    public string? ClientName { get; init; }
    public string? CategoryLineage { get; init; }
    public string? StatusName { get; init; }
    public int WorkflowId { get; init; }
    public string? DisplayId { get; init; }
    public bool Resolved { get; init; }
    public bool IsDeferred { get; init; }
    public int AssigneeType { get; init; }
    public int CallOrigin { get; init; }
    public int AssigneeClientId { get; init; }
    public int AssigneeCallerId { get; init; }
    public string? AssigneeExpression { get; init; }
    public string? AssignedToEmail { get; init; }
    public int IntelligentAssignmentGroup { get; init; }
    public bool IntelligentAssignmentExcludeOutOfOffice { get; init; }
    public string? AssignedToGroupName { get; init; }
    public string? AssignedToIndividualName { get; init; }
    public DateTime ResolvedDate { get; init; }
    public string? AssignedToSummary { get; init; }
    public string? CCAddressList { get; init; }
    public string? DescriptionHtml { get; init; }
    public string? SolutionHtml { get; init; }
    public bool Deleted { get; init; }
    public int NextStepId { get; init; }
    public string? RecordTypeNameSingular { get; init; }
}
