# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
 VivantioApiConsole:
    name: Build VivantioApiConsole
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore WebApp
        run: dotnet restore VivantioApiConsole/VivantioApiConsole.sln

      - name: Build WebApp
        run: dotnet build VivantioApiConsole/VivantioApiConsole.sln --no-restore --configuration Release
